AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Function to get tracks and race counts

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  GetTracksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 512
      Timeout: 300
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: 
            - '*'
      
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./get_tracks
      DockerTag: python3.9-ve1

Outputs:
  GetTracksFunction:
    Description: "GetTracks Lambda Function ARN"
    Value: !GetAtt GetTracksFunction.Arn
  GetTracksFunctionIamRole:
    Description: "Implicit IAM Role created for GetTracks Lambda function"
    Value: !GetAtt GetTracksFunctionRole.Arn
  GetTracksEndpoint:
    Description: "GetTracksFunction Lambda Endpoint URL"
    Value: !GetAtt GetTracksFunctionUrl.FunctionUrl
